### ISSUE TITLE
Support the closed issues event

### ISSUE THREAD

**Issue by Clint-Chester** [synergy-au/Close-Milestone-Action#1]
It would be great if this action was able to support the [issues](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issues) event in workflows. This would allow the action to be used for both pull request and issue events.

**Comment by DanS01** [comment]
Support has been added for the issues event in v1.1 with this [commit](https://github.com/synergy-au/Close-Milestone-Action/commit/3c472949e70a5fb8dae1daf2c6c75211ee112e20).
